### ISSUE TITLE
fails to execute

### ISSUE THREAD

**Issue by bobev18** [mimipaskova/Hexagonal-Minesweeper#1]
###@ubuntu:~/gits/Hexagonal-Minesweeper$ npm start

	> Hexagonal-Minesweeper@0.1.0 start /home/bob/gits/Hexagonal-Minesweeper
	> webpack-dev-server --inline --hot --progress --port 3000

	sh: 1: webpack-dev-server: not found

	npm ERR! Linux 4.13.0-17-generic
	npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
	npm ERR! node v6.11.4
	npm ERR! npm  v3.5.2
	npm ERR! file sh
	npm ERR! code ELIFECYCLE
	npm ERR! errno ENOENT
	npm ERR! syscall spawn
	npm ERR! Hexagonal-Minesweeper@0.1.0 start: `webpack-dev-server --inline --hot --progress --port 3000`
	npm ERR! spawn ENOENT
	npm ERR!
	npm ERR! Failed at the Hexagonal-Minesweeper@0.1.0 start script 'webpack-dev-server --inline --hot --progress --port 3000'.
	npm ERR! Make sure you have the latest version of node.js and npm installed.
	npm ERR! If you do, this is most likely a problem with the Hexagonal-Minesweeper package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     webpack-dev-server --inline --hot --progress --port 3000
	npm ERR! You can get information on how to open an issue for this project with:
	npm ERR!     npm bugs Hexagonal-Minesweeper
	npm ERR! Or if that isn't available, you can get their info via:
	npm ERR!     npm owner ls Hexagonal-Minesweeper
	npm ERR! There is likely additional logging output above.

	npm ERR! Please include the following file with any support request:
	npm ERR!     /home/bob/gits/Hexagonal-Minesweeper/npm-debug.log
	###@ubuntu:~/gits/Hexagonal-Minesweeper$ npm start

	> Hexagonal-Minesweeper@0.1.0 start /home/bob/gits/Hexagonal-Minesweeper
	> webpack-dev-server --inline --hot --progress --port 3000

	sh: 1: webpack-dev-server: not found

	npm ERR! Linux 4.13.0-17-generic
	npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
	npm ERR! node v6.11.4
	npm ERR! npm  v3.5.2
	npm ERR! file sh
	npm ERR! code ELIFECYCLE
	npm ERR! errno ENOENT
	npm ERR! syscall spawn
	npm ERR! Hexagonal-Minesweeper@0.1.0 start: `webpack-dev-server --inline --hot --progress --port 3000`
	npm ERR! spawn ENOENT
	npm ERR!
	npm ERR! Failed at the Hexagonal-Minesweeper@0.1.0 start script 'webpack-dev-server --inline --hot --progress --port 3000'.
	npm ERR! Make sure you have the latest version of node.js and npm installed.
	npm ERR! If you do, this is most likely a problem with the Hexagonal-Minesweeper package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     webpack-dev-server --inline --hot --progress --port 3000
	npm ERR! You can get information on how to open an issue for this project with:
	npm ERR!     npm bugs Hexagonal-Minesweeper
	npm ERR! Or if that isn't available, you can get their info via:
	npm ERR!     npm owner ls Hexagonal-Minesweeper
	npm ERR! There is likely additional logging output above.

	npm ERR! Please include the following file with any support request:
	npm ERR!     /home/###/gits/Hexagonal-Minesweeper/npm-debug.log

**Comment by mimipaskova** [comment]
Have you run `npm install`
It works now (I added two dev dependencies)

If it doesn't work, you reopen the issue.
